apiVersion: seichiclick.seichi.click/v1alpha1
kind: DynamicBungeeCordConfigration
metadata:
  labels:
    app.kubernetes.io/name: dynamicbungeecordconfigration
    app.kubernetes.io/instance: dynamicbungeecordconfigration-sample
    app.kubernetes.io/part-of: seichi-gateway-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: seichi-gateway-operator
  name: dynamicbungeecordconfigration-sample
spec:
  # TODO(user): Add fields here
  # BungeeCordの設定のテンプレート
  # 動的埋め込み部分は以下:
  # - servers[]
  # - listeners.forced_hosts
  bungeeConfigTemplate: |
    server_connect_timeout: 5000
    remote_ping_cache: -1
    forge_support: false
    player_limit: -1
    permissions:
      default:
      - bungeecord.command.server
      - bungeecord.command.list
      admin:
      - bungeecord.command.alert
      - bungeecord.command.end
      - bungeecord.command.ip
      - bungeecord.command.reload
    timeout: 30000
    log_commands: false
    network_compression_threshold: 256
    online_mode: true
    disabled_commands:
    - disabledcommandhere
    servers:
      lobby:
        motd: '&1Just another BungeeCord - Forced Host'
        address: localhost:25565
        restricted: false
      ### ここに動的に設定を埋め込みたい。Reconcile実装の中で文字列操作する ###
    listeners:
    - query_port: 25565
      motd: '&1Another Bungee server'
      tab_list: GLOBAL_PING
      query_enabled: false
      proxy_protocol: false
      forced_hosts:
        pvp.md-5.net: pvp
        ### ここに動的に設定を埋め込みたい。Reconcile実装の中で文字列操作する ###
      ping_passthrough: false
      priorities:
      - lobby
      bind_local_address: true
      host: 0.0.0.0:25565
      max_players: 1
      tab_size: 60
      force_default_server: false
    ip_forward: false
    remote_ping_timeout: 5000
    prevent_proxy_connections: false
    groups:
      md_5:
      - admin
    connection_throttle: 4000
    stats: c4b9cabb-93e9-4bce-93ab-4b18642e6f3e
    connection_throttle_limit: 3
    log_pings: true
  # apply先のconfigmapの情報 具体的には:
  # - namespace.metadata.name
  # - configmap.metadata.name
  # - configmap.data.??? <-どこか
  targetToApplyNamespace: test-gateway
  targetToApplyConfigmapName: bungeecord-config
  targetToApplyConfigmapKey: config.yml
