//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BungeeConfigMapTemplate) DeepCopyInto(out *BungeeConfigMapTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BungeeConfigMapTemplate.
func (in *BungeeConfigMapTemplate) DeepCopy() *BungeeConfigMapTemplate {
	if in == nil {
		return nil
	}
	out := new(BungeeConfigMapTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BungeeConfigMapTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BungeeConfigMapTemplateList) DeepCopyInto(out *BungeeConfigMapTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BungeeConfigMapTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BungeeConfigMapTemplateList.
func (in *BungeeConfigMapTemplateList) DeepCopy() *BungeeConfigMapTemplateList {
	if in == nil {
		return nil
	}
	out := new(BungeeConfigMapTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BungeeConfigMapTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BungeeConfigMapTemplateSpec) DeepCopyInto(out *BungeeConfigMapTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BungeeConfigMapTemplateSpec.
func (in *BungeeConfigMapTemplateSpec) DeepCopy() *BungeeConfigMapTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(BungeeConfigMapTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeichiAssistDebugEnvRequest) DeepCopyInto(out *SeichiAssistDebugEnvRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeichiAssistDebugEnvRequest.
func (in *SeichiAssistDebugEnvRequest) DeepCopy() *SeichiAssistDebugEnvRequest {
	if in == nil {
		return nil
	}
	out := new(SeichiAssistDebugEnvRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeichiAssistDebugEnvRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeichiAssistDebugEnvRequestList) DeepCopyInto(out *SeichiAssistDebugEnvRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeichiAssistDebugEnvRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeichiAssistDebugEnvRequestList.
func (in *SeichiAssistDebugEnvRequestList) DeepCopy() *SeichiAssistDebugEnvRequestList {
	if in == nil {
		return nil
	}
	out := new(SeichiAssistDebugEnvRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeichiAssistDebugEnvRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeichiAssistDebugEnvRequestSpec) DeepCopyInto(out *SeichiAssistDebugEnvRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeichiAssistDebugEnvRequestSpec.
func (in *SeichiAssistDebugEnvRequestSpec) DeepCopy() *SeichiAssistDebugEnvRequestSpec {
	if in == nil {
		return nil
	}
	out := new(SeichiAssistDebugEnvRequestSpec)
	in.DeepCopyInto(out)
	return out
}
